version: '3.8'

services:
  bgm-inserter-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-lisa-research}
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - BGM_S3_BUCKET_NAME=${BGM_S3_BUCKET_NAME}
      - BGM_S3_PREFIX=${BGM_S3_PREFIX:-bgm/}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - ENABLE_S3_UPLOAD=${ENABLE_S3_UPLOAD:-true}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./BGM:/app/BGM:ro  # Keep as fallback
      - ./output_audio:/app/output_audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
