services:
  - type: web
    name: bgm-inserter-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_api.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGINS
        value: "*" 